<a href="https://colab.research.google.com/github/ebaad4000/python/blob/main/Lab_04_20_18SW137.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
x = np.random.random(100)

x

array([0.64784228, 0.41988325, 0.18878122, 0.01803297, 0.35104383,
       0.19485419, 0.64128027, 0.66290587, 0.85674433, 0.35826288,
       0.6199534 , 0.15492792, 0.96521677, 0.15920211, 0.83618446,
       0.15607473, 0.94353318, 0.27556085, 0.23861253, 0.22814618,
       0.39402737, 0.22191571, 0.32150102, 0.12054398, 0.51557709,
       0.66705075, 0.67452289, 0.13837936, 0.39654699, 0.76570149,
       0.84450422, 0.91485975, 0.79620209, 0.52685414, 0.46258112,
       0.75937342, 0.86818216, 0.95903833, 0.06346152, 0.35545507,
       0.15230706, 0.09789183, 0.34522053, 0.39587245, 0.20120865,
       0.06692539, 0.22351137, 0.10411008, 0.80946004, 0.25370628,
       0.66897869, 0.23423876, 0.27494295, 0.07875566, 0.95088984,
       0.684038  , 0.1752556 , 0.73306211, 0.92729527, 0.17809045,
       0.26242517, 0.31177593, 0.05504317, 0.261121  , 0.25335494,
       0.11934821, 0.0772446 , 0.38248498, 0.11587931, 0.89658995,
       0.92495339, 0.08205276, 0.97281295, 0.11230313, 0.93991

In [8]:
v = np.eye(6)

In [ ]:
v

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
b = np.diag(v)

In [ ]:
b

array([1., 1., 1., 1., 1.])

In [10]:
n = np.diff(v)

In [ ]:
n

array([[-1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  1.]])

In [11]:
m = np.arange(1,10)

In [ ]:
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.save("x_data",m)

In [ ]:
s= np.random.randint(32)

In [ ]:
s

10

In [ ]:
r2array = np.append(n, [[5,5,5,4],], 0)

In [ ]:
r2array

array([[-1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.],
       [ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  1.],
       [ 5.,  5.,  5.,  4.]])

In [24]:
d = n[3:,:4]
d

array([[ 0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:

f = np.sort(r2array)

f

In [ ]:
array1 = np.array([1,5])
array2 = np.array([4,4,4])

In [ ]:
np.add(array1,array2) # Broadcasting needed

ValueError: ignored

In [ ]:
g = n.mean()

In [ ]:
g

0.0

Lab Tasks:

Task # 01:

In [ ]:
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)

print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task # 02:

In [ ]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print("Original Array:")
print(X)

print("\nArray with Odd Numbers:")
print(Y)


Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with Odd Numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task # 03:

In [ ]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray with consecutive columns
X = np.arange(1, 5)[:, np.newaxis] * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


 Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero.

To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [ ]:
# import NumPy into Python

import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
lower_bound = 0
upper_bound = 5001
array_shape = (1000, 20)

X = np.random.randint(lower_bound, upper_bound, size=array_shape)

# print the shape of X
print("Shape of random_array:", X.shape)

Shape of random_array: (1000, 20)


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:
     
  $\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$.

In [ ]:
# Average of the values in each column of X
ave_cols = np.mean(X, axis=0)
# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [ ]:
# Print the shape of ave_cols
print("Shape of column_averages:", ave_cols.shape)

# Print the shape of std_cols
print("Shape of column_stddevs:", std_cols.shape)

Shape of column_averages: (20,)
Shape of column_stddevs: (20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [ ]:
# Calculate the mean of each column
column_means = np.mean(X, axis=0)

# Mean normalize X
X_norm = X - column_means

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [ ]:
# Print the average of all the values of X_norm
average_mean_normalized = np.mean(X_norm)

# Print the average of the minimum value in each column of X_norm
average_min_value = np.mean(np.min(X_norm, axis=0))

# Print the average of the maximum value in each column of X_norm
average_max_value = np.mean(np.max(X_norm, axis=0))

You should note that since $X$ was created using random integers, the above values will vary.

 Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data.

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [ ]:
# We create a random permutation of integers 0 to 4
np.random.permutation(5)

array([2, 4, 3, 1, 0])


 To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [ ]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
random_permutation = np.random.permutation(X_norm.shape[0])

Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [ ]:
# Make any necessary calculations.

# Calculate the indices for splitting the data
train_size = int(0.6 * random_permutation.shape[0])
cross_val_size = int(0.2 * random_permutation.shape[0])

# You can save your calculations into variables to use later.

# Create a Training Set
X_train = X_norm[random_permutation[:train_size]]

# Create a Cross Validation Set
X_crossVal = X_norm[random_permutation[train_size : train_size + cross_val_size]]

# Create a Test Set
X_test = X_norm[random_permutation[train_size + cross_val_size:]]

If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [ ]:
# Print the shape of X_train
print("Shape of X_train:", X_train.shape)

# Print the shape of X_crossVal
print("Shape of X_crossVal:", X_crossVal.shape)

# Print the shape of X_test
print("Shape of X_test:", X_test.shape)

Shape of X_train: (600, 20)
Shape of X_crossVal: (200, 20)
Shape of X_test: (200, 20)
